In [1]:
import pandas as pd

# temporary formatting purposes
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [2]:
data = pd.read_csv("professors_info.csv")
data.head()

,SID,School Name,Professor Name,Overall Quality,Num Reviews,Department,Class Taken,Review Date,Quality,Difficulty,Review Text
0,1147,Washington University in St. Louis,Karl Schaefer,4.8,20,Mathematics,MATH233,"Sep 6th, 2024",5.0,2.0,"Best Professor I've Ever Had. He explains complex concepts with such clarity and depth that everything feels understandable. What truly sets him apart is how deeply he cares about his students. His kindness and compassion create an incredibly supportive learning environment. On top of that, he's hilarious, making class not only informative but fun!"
1,1147,Washington University in St. Louis,Karl Schaefer,4.8,20,Mathematics,MATH233,"Jun 14th, 2024",5.0,2.0,Probably one of the best math professors at wash
2,1147,Washington University in St. Louis,Karl Schaefer,4.8,20,Mathematics,MATH310W,"Jun 4th, 2024",5.0,2.0,"Schaefer is a very skilled educator and he is very qualified to teach the sensitive 310W. Schaefer's 310 included a good coverage of foundational topics. The class is very difficult, that's just the nature of it. Schaefer doesn't seem to hold punches but still gives exceptional lectures and is very accessible and helpful outside of class."
3,1147,Washington University in St. Louis,Karl Schaefer,4.8,20,Mathematics,MATH233,"Jun 4th, 2024",5.0,2.0,Schaefer remains unparalleled for Calculus lectures. Precup was also very good.
4,1147,Washington University in St. Louis,Karl Schaefer,4.8,20,Mathematics,MATH233,"May 22nd, 2024",5.0,2.0,Professor Schaefer is an amazing Professor. He is very organized and gives practice tests and quizzes to help people succeed.

<h1>Data Pre-Processing</h1>

Convert all course codes to uppercase

In [5]:
data['Class Taken'] = data['Class Taken'].str.upper()

If the course code ends with a letter, remove it.
<br>
Example: CHEM111A --> Chem111

In [7]:
data['Class Taken'] = data['Class Taken'].str.replace(r'[A-Z]$', '', regex=True)

Remove rows where the class taken is not given (empty Class Taken)
<br>
There is only one empty course title, so this is feasible

In [9]:
data = data[data['Class Taken'].str.strip() != '']

Let's use fuzzy matching NLP to group course codes within each department that share at least a 92% similarity. <br>
This will standardize course codes to a single common course code, if they're similar enough

Example:<br>
CHEM111 and CHM111 --> CHEM111

In [11]:
from fuzzywuzzy import process

In [12]:
def similar_course_mapper(department):
    unique_courses = department['Class Taken'].unique()
    course_map = {}
    
    for course in unique_courses:
        # find the closest matches to each course within the department
        matches = process.extract(course, unique_courses)
        # group courses together if they have a similarity score >= 92/100%
        similar_courses = [match for match, score in matches if score >= 92]
        
        if similar_courses:
            # if a similar course grouping exists --> the new course code will be the most popular course code of that group
            most_frequent_course = department[department['Class Taken'].isin(similar_courses)]['Class Taken'].mode()
            if len(most_frequent_course) > 0:
                most_frequent_course_value = most_frequent_course[0]
                for similar_course in similar_courses:
                    course_map[similar_course] = most_frequent_course_value
                    
    return course_map

In [13]:
# apply the function above to get the correct course code mappings within each department
course_corrections = data.groupby('Department').apply(similar_course_mapper, include_groups=False).to_dict()

In [14]:
# get the corrected course code for each row based on the department and class taken, otherwise default original course code
def correct_courses(row, corrections):
    return corrections.get(row['Department'], {}).get(row['Class Taken'], row['Class Taken'])

In [15]:
# apply the function above to correct the course codes
data['Class Taken Corrected'] = data.apply(correct_courses, corrections=course_corrections, axis=1)

Only allow keep course codes that match the following format: [A-Z]+[0-9]{3,4}[A-Z]?

In other words, only keep course codes that start with alphabetical letters, followed by 3-4 digits, and an optional alphabetical letter indicating a type of course (i.e. T, M, A, S, D)

Examples:
Accepted Course Codes: CSE330S, CSE217A, CSE240
Not Accepted Course Codes: 100B, 100, B

In [17]:
course_code_pattern = r'^[A-Z]+[0-9]{3,4}[A-Z]?$'

print(data.shape)
data = data[data['Class Taken'].str.contains(course_code_pattern, regex=True)]
print(data.shape)

(6443, 12)
(4857, 12)

In [18]:
data[["Class Taken", "Class Taken Corrected"]]

         Class Taken Class Taken Corrected
0            MATH233               MATH233
1            MATH233               MATH233
2            MATH310               MATH310
3            MATH233               MATH233
4            MATH233               MATH233
5            MATH233               MATH233
6            MATH233               MATH233
7            MATH233               MATH233
8            MATH233               MATH233
9            MATH233               MATH233
10           MATH233               MATH233
11           MATH132               MATH132
12           MATH233               MATH233
13           MATH132               MATH132
14          MATH4351              MATH4351
15           MATH132               MATH132
16           MATH100               MATH100
17           MATH132               MATH132
18           MATH132               MATH132
19           MATH132               MATH132
20           CHEM151               CHEM151
21           CHEM152               CHEM152
22           CHEM152               CHEM152
24           CHEM151               CHEM151
25           CHEM151               CHEM151
26           CHEM151               CHEM151
27           CHEM151               CHEM151
28           CHEM151               CHEM151
29           CHEM151               CHEM151
30           CHEM151               CHEM151
31           CHEM151               CHEM151
32           CHEM126               CHEM126
34           CHEM152               CHEM152
35           CHEM152               CHEM152
36           CHEM151               CHEM151
37           CHEM151               CHEM151
38           CHEM151               CHEM151
39           CHEM151               CHEM151
40          MATH4351              MATH4351
41           MATH132               MATH132
42          MATH4351              MATH4351
43          MATH4351              MATH4351
44           MATH132               MATH132
45          MATH4351              MATH4351
46          MATH4351              MATH4351
47          MATH4351              MATH4351
48          MATH4351              MATH4351
49          MATH4351              MATH4351
50          MATH4351              MATH4351
51          MATH4351              MATH4351
52          MATH4351              MATH4351
53          MATH4351              MATH4351
54          MATH4351              MATH4351
55          MATH4351              MATH4351
56           MATH131               MATH131
57           MATH131               MATH131
58           MATH131               MATH131
59           MATH132               MATH132
60           CHEM111               CHEM111
61           CHEM111               CHEM111
62           CHEM111               CHEM111
63           CHEM111               CHEM111
64           CHEM111               CHEM111
65           CHEM111               CHEM111
66           CHEM111               CHEM111
67           CHEM111               CHEM111
68           CHEM111               CHEM111
69           CHEM111               CHEM111
70           CHEM111               CHEM111
71           CHEM111               CHEM111
72           CHEM111               CHEM111
74           CHEM111               CHEM111
76           CHEM111               CHEM111
77           CHEM111               CHEM111
78           CHEM111               CHEM111
79           CHEM111               CHEM111
83          PSYCH100              PSYCH100
89          PSYCH100              PSYCH100
91          PSYCH100              PSYCH100
92          PSYCH100              PSYCH100
94          PSYCH100              PSYCH100
95          PSYCH100              PSYCH100
97          PSYCH100              PSYCH100
98          PSYCH100              PSYCH100
99          PSYCH100              PSYCH100
100          ANTH361               ANTH361
101          ANTH361               ANTH361
102          ANTH361               ANTH361
103        ANTHRO361             ANTHRO361
104          ANTH361               ANTH361
105          ANTH361               ANTH361
106          ANTH361               ANTH361
107         ANTHR361               ANTH361
109          ANTH361               ANTH361
110       CULTENV361            CULTENV361
112         ENST3322              ENST3322
116          ANTH361               ANTH361
117          ANTH361               ANTH361
118          BNC3322               BNC3322
119         ANTHR361               ANTH361
120          BIOL324               BIOL324
121          BIOL324               BIOL324
122         BIOL2970               BIO2970
123          BIO2970               BIO2970
124          BIO2970               BIO2970
125          BIO2970               BIO2970
126          BIO2970               BIO2970
127          BIO2970               BIO2970
128          BIO2970               BIO2970
129          BIO2970               BIO2970
130          BIO2970               BIO2970
131          BIO2970               BIO2970
132          BIO2970               BIO2970
133          BIO2970               BIO2970
134          BIO2970               BIO2970
135          BIO2970               BIO2970
136          BIO2970               BIO2970
137          BIO2970               BIO2970
138          BIO2970               BIO2970
139          BIO2970               BIO2970
141          WGS3103               WGS3103
142          WGSS393               WGSS393
143           WGS100               WGSS100
144           IPH201                IPH201
145          WGSS393               WGSS393
146          WGSS100               WGSS100
148          WGSS393               WGSS393
149          WGSS100               WGSS100
151          WGSS100               WGSS100
152          WGSS100               WGSS100
153          WGSS100               WGSS100
154          ELIT395               ELIT395
156          WGSS393               WGSS393
157          WGSS393               WGSS393
160          CHEM111               CHEM111
161          CHEM111               CHEM111
162          CHEM111               CHEM111
163          CHEM111               CHEM111
164          CHEM111               CHEM111
165          CHEM111               CHEM111
166          CHEM111               CHEM111
167          CHEM111               CHEM111
168          CHEM111               CHEM111
169          CHEM111               CHEM111
170          CHEM111               CHEM111
171          CHEM111               CHEM111
172          CHEM111               CHEM111
173          CHEM106               CHEM106
174          CHEM111               CHEM111
175          CHEM111               CHEM111
176          CHEM111               CHEM111
177          CHEM111               CHEM111
178          CHEM111               CHEM111
179          CHEM106               CHEM106
180          CHEM228               CHEM228
181          CHEM252               CHEM252
182          CHEM251               CHEM251
183          CHEM257               CHEM257
185          CHEM257               CHEM257
186          CHEM257               CHEM257
189          CHEM251               CHEM251
190          CHEM251               CHEM251
191          CHEM251               CHEM251
192          CHEM251               CHEM251
193          CHEM251               CHEM251
194          CHEM251               CHEM251
196          CHEM251               CHEM251
197          CHEM251               CHEM251
199          CHEM251               CHEM251
200            CS240                 CS240
201            CS240                 CS240
202            CS240                 CS240
203            CS240                 CS240
204            CS240                 CS240
205            CS240                 CS240
206            CS240                 CS240
207           CSE240                CSE240
208            CS240                 CS240
209            CS240                 CS240
210            CS240                 CS240
211            CS240                 CS240
212            CS240                 CS240
213            CS240                 CS240
214            CS240                 CS240
215           CSE240                CSE240
216            CS240                 CS240
217            CS240                 CS240
218           CSE240                CSE240
219            CS240                 CS240
220           DAT121                DAT121
221           DAT121                DAT121
222           DAT121                DAT121
223           DAT121                DAT121
224           DAT121                DAT121
225           DAT121                DAT121
226           DAT121                DAT121
227           DAT121                DAT121
228           DAT121                DAT121
229           DAT121                DAT121
230           DAT121                DAT121
231           DAT121                DAT121
232           DAT121                DAT121
233           DAT121                DAT121
234           DAT121                DAT121
235           DAT121                DAT121
236           DAT121                DAT121
237           DAT121                DAT121
238           QBA121                QBA121
239           QBA121                QBA121
240          CHEM358               CHEM358
241          CHEM358               CHEM358
242          CHEM358               CHEM358
243           CHE262               CHEM262
244          ORGO252               ORGO252
245           CHE262               CHEM262
246          CHEM262               CHEM262
247          CHEM262               CHEM262
248          CHEM262               CHEM262
249          CHEM262               CHEM262
250          CHEM262               CHEM262
251          CHEM262               CHEM262
252          CHEM262               CHEM262
253           CHE262               CHEM262
254          CHEM262               CHEM262
255          CHEM261               CHEM261
256          CHEM262               CHEM262
257          ORGO252               ORGO252
258          ORGO252               ORGO252
259          CHEM252               CHEM252
260           MKT370                MKT370
261           MKT370                MKT370
262           MKT370                MKT370
263           MKT477                MKT477
264           MKT370                MKT370
265           MKT370                MKT370
266          MKTG370                MKT370
267           MKT481                MKT481
268           MKT447                MKT447
269           MKT378                MKT378
270           MKT300                MKT300
271           MKT300                MKT300
272           MKT300                MKT300
273           MKT370                MKT370
274           MKT481                MKT481
275           MKT370                MKT370
276           MKT370                MKT370
278           MKT370                MKT370
279           MKT370                MKT370
280           CSE362                CSE362
282           CSE260                CSE260
283           CSE260                CSE260
286           CSE260                CSE260
287           CSE260                CSE260
288           CSE260                CSE260
289           CSE260                CSE260
290           CSE260                CSE260
291           CSE260                CSE260
293           CSE260                CSE260
294           CSE260                CSE260
295           DSS101                DSS101
296           CSE260                CSE260
297           ESE260                ESE260
298           CSE362                CSE362
299           CSE260                CSE260
300         BIOL4580              BIOL4580
301        ANTHRO150             ANTHRO150
302        ANTHRO150             ANTHRO150
303        ANTHRO150             ANTHRO150
304        ANTHRO150             ANTHRO150
305        ANTHRO150             ANTHRO150
306        ANTHRO150             ANTHRO150
307        ANTHRO150             ANTHRO150
308       ANTHRO4581            ANTHRO4581
309       ANTHRO4581            ANTHRO4581
310        ANTHRO150             ANTHRO150
311        ANTHRO150             ANTHRO150
312        ANTHRO150             ANTHRO150
313        ANTHRO150             ANTHRO150
314        ANTHRO150             ANTHRO150
315        ANTHRO150             ANTHRO150
316        ANTHRO150             ANTHRO150
317        ANTHRO150             ANTHRO150
318        ANTHRO150             ANTHRO150
319        ANTRHO150             ANTRHO150
320          AFAS322               AFAS322
321          AFAS321               AFAS321
322          AFAS192               AFAS192
323          HIST395               HIST395
324         HIST3622              HIST3622
325          AFAS321               AFAS321
326       HISTORY164            HISTORY164
327       HISTORY164            HISTORY164
328          AFAS321               AFAS321
330          HIST164               HIST164
331          HIST164               HIST164
332          HIST164               HIST164
333          AFAS321               AFAS321
343         LOGIC100              LOGIC100
344          PHIL100               PHIL100
345          PHIL100               PHIL100
346          PHIL100               PHIL100
347         LOGIC100              LOGIC100
348          PHIL101               PHIL101
349         LOGIC100              LOGIC100
350          PHIL101               PHIL101
352          PHIL100               PHIL100
353          PHIL100               PHIL100
354          PHIL100               PHIL100
355         LOGIC100              LOGIC100
356         LOGIC100              LOGIC100
357          PHIL100               PHIL100
358          PHIL100               PHIL100
359          PHIL100               PHIL100
364          PHYS126               PHYS126
365          PHYS126               PHYS126
366           PHY126               PHYS126
367          PHYS126               PHYS126
368          PHYS126               PHYS126
369          PHYS126               PHYS126
370          PHYS126               PHYS126
371       PHYSICS126           PHYSICS-126
372          PHYS126               PHYS126
373          PHYS126               PHYS126
377       PHYSICS125            PHYSICS125
378       PHYSICS125            PHYSICS125
379       PHYSICS125            PHYSICS125
380           MGT100                MGT100
381           MGT100                MGT100
382           MGT100                MGT100
383           MGT100                MGT100
384           MGT100                MGT100
385           MGT100                MGT100
386           MGT100                MGT100
387           MGT100                MGT100
388           MGT100                MGT100
389           MGT100                MGT100
390           MGT100                MGT100
391           MGT100                MGT100
392           MGT100                MGT100
393           MGT100                MGT100
394           MGT100                MGT100
395           MGT100                MGT100
396         MNGMT100              MNGMT100
397           MGT100                MGT100
398           MGT100                MGT100
399           MGT100                MGT100
400          MATH132               MATH132
401          MATH310               MATH310
402          MATH310               MATH310
403          MATH310               MATH310
404          MATH203               MATH203
405          MATH233               MATH233
406         MATH4171               MATH417
407          MATH233               MATH233
408          MATH233               MATH233
409          MATH233               MATH233
410          MATH233               MATH233
411          MATH233               MATH233
412          CALC233               CALC233
413          MATH233               MATH233
414          MATH233               MATH233
415          MATH233               MATH233
416          MATH233               MATH233
417          MATH233               MATH233
418          CALC233               CALC233
419          MATH233               MATH233
420          PHIL340               PHIL340
421          PHIL131               PHIL131
422          PHIL345               PHIL345
423          PHIL131               PHIL131
424            LW131                 LW131
425          PHIL131               PHIL131
426          PHIL131               PHIL131
427          PHIL131               PHIL131
428          PHIL131               PHIL131
429          LWST131               LWST131
430          PHIL131               PHIL131
431          LWST131               LWST131
432          PHIL131               PHIL131
433          PHIL131               PHIL131
434          PHIL101               PHIL101
435          PHIL131               PHIL131
436            LW131                 LW131
437          PHIL131               PHIL131
439          PHIL345               PHIL345
440          CHEM152               CHEM152
441          CHEM152               CHEM152
442          CHEM152               CHEM152
443          CHEM152               CHEM152
444          CHEM152               CHEM152
445          CHEM151               CHEM151
446          CHEM152               CHEM152
447          CHEM151               CHEM151
448          CHEM151               CHEM151
449          CHEM151               CHEM151
450          CHEM151               CHEM151
451          CHEM151               CHEM151
452          CHEM152               CHEM152
453          CHEM151               CHEM151
454          CHEM151               CHEM151
455          CHEM151               CHEM151
456          CHEM151               CHEM151
457          CHEM151               CHEM151
458          CHEM151               CHEM151
459          CHEM152               CHEM152
460           PHY107               PHYS107
461       PHYSICS506            PHYSICS506
462       PHYSICS506            PHYSICS506
463             L125                  L125
464       PHYSICS506            PHYSICS506
465             L125                  L125
466          PHYS107               PHYS107
467          PHYS107               PHYS107
468          PHYS101               PHYS101
469          PHYS101               PHYS101
470          PHYS101               PHYS101
474          PHYS107               PHYS107
479           PHY107               PHYS107
484         ANTHR362              ANTHR362
485         ANTHR362              ANTHR362
492        ANTHRO362             ANTHRO361
496        ANTHRO362             ANTHRO361
498           ANT406                ANT406
499           ANT444                ANT444
502         LATIN102              LATIN102
503          LATN316               LATN316
504           LTN217                LTN217
505          LATN316               LATN316
506           HUM201                HUM201
508         LATIN100              LATIN100
514           HUM203                HUM203
520          HIST101               HIST101
521          HIST301               HIST101
522          HIST101               HIST101
523          HIST101               HIST101
525         HIST4653              HIST4653
526          HIST102               HIST102
528          HIST101               HIST101
529          HIST101               HIST101
530          HIST101               HIST101
531          HIST101               HIST101
532          HIST101               HIST101
533          HIST101               HIST101
535          HIST398              HIST3598
537          HIST101               HIST101
538          HIST101               HIST101
539          HIST101               HIST101
540          CHEM261               CHEM261
541          CHEM261               CHEM261
543          CHEM261               CHEM261
544          CHEM261               CHEM261
545          CHEM261               CHEM261
546          CHEM261               CHEM261
547          CHEM261               CHEM261
549          CHEM251               CHEM251
550          CHEM261               CHEM261
551          CHEM251               CHEM251
552          CHEM251               CHEM251
554          CHEM251               CHEM251
555          CHEM251               CHEM251
556          CHEM251               CHEM251
557          CHEM251               CHEM251
559          CHEM251               CHEM251
560           CSE365                CSE365